# Generated by Django 5.2.17 on 2026-08-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='System', max_length=150)),
                ('role', models.CharField(default='Resident', max_length=50)),
                ('action', models.CharField(choices=[('USER_REGISTRATION', 'User Registration'), ('ROLE_CHANGE', 'Role Change'), ('INCIDENT_REPORTED', 'Incident Reported'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('SOS_TRIGGERED', 'SOS Alert Triggered'), ('ANNOUNCEMENT_PUBLISHED', 'Announcement Published'), ('EVENT_CREATED', 'Event Created'), ('VERIFICATION_APPROVED', 'Verification Approved')], max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
