# Generated by Django 4.2.30 on 2026-08-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMERGENCY', 'Emergency SOS Alert'), ('ANNOUNCEMENT', 'Community Announcement'), ('INCIDENT', 'Incident Report Update'), ('EVENT', 'Community Event Update'), ('MEMBERSHIP', 'Membership Request'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
    ]
