# Generated by Django 4.2.30 on 2026-08-14 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical Services'), ('GARDENING', 'Gardening & Landscaping'), ('SECURITY', 'Private Security / Patrol'), ('CLEANING', 'Home & Office Cleaning'), ('HANDYMAN', 'Handyman & Repairs'), ('TUTORING', 'Educational Tutoring'), ('OTHER', 'Other Local Services')], default='OTHER', max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='LostAndFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item')], default='LOST', max_length=10)),
                ('category', models.CharField(choices=[('PETS', 'Pets & Animals'), ('ELECTRONICS', 'Electronics & Gadgets'), ('KEYS', 'Keys & Cards'), ('DOCUMENTS', 'Documents & Wallets'), ('CLOTHING', 'Clothing & Accessories'), ('OTHER', 'Other Items')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_and_found_items', to='communities.community')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
    ]
