# Generated by Django 4.2.30 on 2026-08-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('CRIME', 'Crime & Theft'), ('FIRE', 'Fire Emergency'), ('MEDICAL', 'Medical Emergency'), ('INFRASTRUCTURE', 'Infrastructure Damage'), ('WATER', 'Water Service Outage / Leak'), ('ELECTRICITY', 'Electricity Outage / Fault'), ('DUMPING', 'Illegal Dumping'), ('NOISE', 'Noise Complaint'), ('SUSPICIOUS', 'Suspicious Activity'), ('OTHER', 'Other Incident')], default='SUSPICIOUS', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='REPORTED', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='communities.community')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
    ]
