# Generated by Django 5.2.17 on 2026-08-26 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=-25.7461)),
                ('longitude', models.FloatField(default=28.1881)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dispatched', 'Dispatched'), ('Resolved', 'Resolved')], default='Active', max_length=50)),
                ('time_activated', models.DateTimeField(auto_now_add=True)),
                ('time_resolved', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='communities.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
